### ISSUE TITLE
代码重构

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-pkg/radxa-otgutils#11]
目前的以太网服务是ECM，需要添加USB NCM的支持

- [ ] 脚本重构，主脚本的命令可以精细的单独开关UDC和单独配置某个功能。功能的具体实现则是由单独的模块文件提供，通过提供一些回调函数来实现
- [x] 服务重构，服务添加一个radxa-otgutils@服务或者是target，依赖于现有的两个服务。然后这个新服务只负责开关UDC，现有的服务只负责功能的配置，以解决Amlogic上只能开启一次UDC的问题
- [x] 添加radxa-ncm@服务

**Comment by RadxaYuntian** [comment]
@RadxaNaoki confirmed that only the GADGET needs to be changed to support NCM: https://github.com/RadxaNaoki/radxa-otgutils/commit/b8872bc4e8c343a91e7e40f514dd9012cab307e0

**Comment by RadxaNaoki** [comment]
and CONFIG_USB_CONFIGFS_NCM=y https://github.com/RadxaNaoki/bsp/commit/1f50848cbd0c0c0690db1e7adfefc7d490b38520

**Comment by RadxaYuntian** [comment]
Done in https://github.com/radxa-repo/bsp/commit/32995a18f53dae3f41e4bb354e301ba4ecb69471

**Comment by CodeChenL** [comment]
$1添加udc选项：Usage: $0 <adbd|usbnet|udc> <UDC> <start|stop|restart>

**Comment by CodeChenL** [comment]
task1是否可以理解为，$1添加udc选项,如下：
```bash
Usage: $0 <adbd|usbnet|udc> <start|stop|restart>
```

**Comment by RadxaYuntian** [comment]
差不多，所以之后就是先是adbd和usbnet的服务单独处理完start,再来udc start
另外模块看了下可能不一定有必要

**Comment by CodeChenL** [comment]
添加ECM支持，还需要保留NCM功能吗

**Comment by RadxaYuntian** [comment]
添加NCM,并且保留ECM
