### ISSUE TITLE
adbd not running on radxa zero

### ISSUE THREAD

**Issue by MPC-BlackBox** [radxa-pkg/radxa-otgutils#2]
Hi.

I have a RadXa Zero running 5.10.134-meson64.

I am trying to get adb working. The base system does not have amlogic-adbd service loaded.

I tried:

_sudo apt install -y wget
wget https://github.com/radxa-pkg/radxa-otgutils/releases/download/0.2.2/radxa-otgutils_0.2.2_all.deb
sudo dpkg -i radxa-otgutils_0.2.2_all.deb
sudo systemctl enable radxa-usbnet.service
_

I then did a system reboot.

I tried adb devices but that does not work and the following error shows on the Zero when using the command:

sudo systemctl status radxa-adbd

Error is "Did not find adbd. Please check if related packages are installed."

Any ideas?

**Comment by RadxaYuntian** [comment]
`radxa-otgutils` is currently supported in `rbuild` system only. As for `adbd` you can find the upstream packages [here](https://github.com/radxa-pkg/android-tools-adbd/releases/tag/5.1.1.r38-1.1).

**Comment by MPC-BlackBox** [comment]
Hi.

How do I install rbuild? Is there a binary image I can download to a Zero?

**Comment by RadxaYuntian** [comment]
[`rbuild`](https://github.com/radxa-repo/rbuild) is our system building tool. Currently we only have [test builds](https://github.com/radxa-build/radxa-zero/releases) for Zero based on `rbuild`.
